# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import account_pb2 as account__pb2


class checkStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Check = channel.unary_unary(
        '/check/Check',
        request_serializer=account__pb2.Account.SerializeToString,
        response_deserializer=account__pb2.Response.FromString,
        )


class checkServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Check(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_checkServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Check': grpc.unary_unary_rpc_method_handler(
          servicer.Check,
          request_deserializer=account__pb2.Account.FromString,
          response_serializer=account__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'check', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
